#!/bin/bash

url=$1

if [ -z $url ]; then
	exit 0
fi

get_s3() {
	s3path=$1
	filename=$2
	aws s3 cp $s3path $filename
}

put_s3() {
	s3path=$1
	filename=$2
	aws s3 cp $filename $s3path
}


urlid=$(echo -n "$url" | md5sum)

tempfile=$(mktemp)

cached_url="s3://${BUILD_CACHE_BUCKET}/cache/$urlid"

get_s3 $cached_url $tempfile

if [ $? -gt 0 ]; then
	>&2 echo "Retrieving $@ into build cache"
	curl -ssS $@ -o $tempfile
	put_s3 $cached_url $tempfile
fi

cat $tempfile && rm $tempfile